version: '3'
  db:
    image: mysql
    container_name: api-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
    ports:
      - "3306:3306"
    volumes:
      - ./:/var/lib/mysql/data
    networks:
      - mysql-compose-network
      
      
      
  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - mysql-compose-network
